version: 2

jobs:
  build-common: &common-build
    docker:
      - image: node
    working_directory: ~/mini-mocha
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v3-npm-{{ .Branch }}-{{ checksum "package.json" }}
            - v3-npm-master-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Pre-Test
          command: |
              npm run lint
      - run:
          name: Test
          command: |
            # Preferably, just run unit tests. Not quite there, yet :-)
            npm test

            # Check output using stable Node version
            if node --version | grep -q '^v12'; then
              echo "This is where we should test the output"
            fi

      - save_cache:
          key: v3-npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

  node-10:
    <<: *common-build
    docker:
      - image: node:10

  node-12:
    <<: *common-build
    docker:
      - image: node:12

workflows:
  version: 2
  build:
    jobs:
      - node-10
      - node-12
